In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('ABT_F2.csv', encoding='big5')

In [4]:
# 指定要替換空值的欄位
columns_to_fill = ['A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10', 'A11', 'A12', 
                   'A13', 'A14', 'A15', 'A17', 'A18', 'A19', 'A21', 'A22', 'A23', 'A24', 'A99', 
                   'C01', 'C02', 'C03', 'C04', 'C05', 'C06', 'D01', 'D02', 'D03', 'D04', 'D05', 
                   'D06', 'D07', 'D08', 'D09', 'D10', 'D12', 'D13', 'D51', 'D53', 'D55', 'D56', 
                   'D57', 'D58', 'D59', 'D60', 'D61', 'D62', 'D63', 'D65', 'D66','N_POLICY_NO', 'SUM_of_HOSPITAL', 'SUM_of_SURGERY',
       'SUM_of_PAYG', 'SUM_of_IS_SERIOUS', 'SUM_of_SERIOUS_CANCER',
       'SUM_of_IS_ACCIDENT', 'SUM_of_IS_LONG', 'SUM_of_IS_LIFE',
       'COUNT_A_ACCIDENT', 'COUNT_D_LIFE', 'COUNT_FR_FIXED_RATE',
       'COUNT_H_HOSPITAL', 'COUNT_I_INVESTMENT', 'COUNT_IS_VARIABLE_RATE',
       'COUNT_L_LONGTERM_CARE', 'COUNT_M_MAJOR_ILLNESS',
       'COUNT_R_REIMBURSEMENT', 'COUNT_S_SURGERY', 'COUNT_W_WAIVER',
       'COUNT_Z_OTHER']

# 將指定欄位的空值替換為0
df[columns_to_fill] = df[columns_to_fill].fillna(0)

In [5]:
df.head()

,ID,FIRSTDT,DAY_DIFF,SOURCE,IS_CONTRACT_APC,IS_CONTRACT_INC,IS_EMP,IS_CLAIM,IS_FB,IS_MEMBER,...,COUNT_FR_FIXED_RATE,COUNT_H_HOSPITAL,COUNT_I_INVESTMENT,COUNT_IS_VARIABLE_RATE,COUNT_L_LONGTERM_CARE,COUNT_M_MAJOR_ILLNESS,COUNT_R_REIMBURSEMENT,COUNT_S_SURGERY,COUNT_W_WAIVER,COUNT_Z_OTHER
0,#005432F5B4D312911,05JUN1993,11349,意外險,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,#010A3014A265DF94D,19APR1993,11396,意外險,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,#02238ADE059241E68,16JUN1993,11338,意外險,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,#023D96CE3BF169959,05JUN1993,11349,意外險,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,#0328BA853B310F5DF,16JUN1993,11338,意外險,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
#欄位名稱
df.columns

Index(['ID', 'FIRSTDT', 'DAY_DIFF', 'SOURCE', 'IS_CONTRACT_APC',
       'IS_CONTRACT_INC', 'IS_EMP', 'IS_CLAIM', 'IS_FB', 'IS_MEMBER', 'IS_MML',
       'IS_ACC', 'MAX_RGN_CODE', 'MAX_RGN_PLACE', 'MAX_ISSUE_DAYS',
       'SUM_ISSUE_DAYS', 'SUM_of_STEP', 'HIGH_LV', 'A01', 'A02', 'A03', 'A04',
       'A05', 'A06', 'A07', 'A08', 'A09', 'A10', 'A11', 'A12', 'A13', 'A14',
       'A15', 'A17', 'A18', 'A19', 'A21', 'A22', 'A23', 'A24', 'A99', 'C01',
       'C02', 'C03', 'C04', 'C05', 'C06', 'D01', 'D02', 'D03', 'D04', 'D05',
       'D06', 'D07', 'D08', 'D09', 'D10', 'D12', 'D13', 'D51', 'D53', 'D55',
       'D56', 'D57', 'D58', 'D59', 'D60', 'D61', 'D62', 'D63', 'D65', 'D66',
       'EFT_CUST', 'N_POLICY_NO', 'SUM_of_HOSPITAL', 'SUM_of_SURGERY',
       'SUM_of_PAYG', 'SUM_of_IS_SERIOUS', 'SUM_of_SERIOUS_CANCER',
       'SUM_of_IS_ACCIDENT', 'SUM_of_IS_LONG', 'SUM_of_IS_LIFE',
       'COUNT_A_ACCIDENT', 'COUNT_D_LIFE', 'COUNT_FR_FIXED_RATE',
       'COUNT_H_HOSPITAL', 'COUNT_I_INVESTMENT', 'COUNT_IS_VARIABLE_RATE',
       'COUNT_L_LONGTERM_CARE', 'COUNT_M_MAJOR_ILLNESS',
       'COUNT_R_REIMBURSEMENT', 'COUNT_S_SURGERY', 'COUNT_W_WAIVER',
       'COUNT_Z_OTHER'],
      dtype='object')

In [7]:
df_unique = df.sort_values('HIGH_LV', ascending=False).drop_duplicates('ID', keep='first')

In [8]:
# df_unique.to_csv('ABT.csv',index=False)

In [9]:
# 數位客戶
df = df_unique[df_unique['IS_MEMBER']==1]
len(df)

4209793

In [10]:
# 分位數會沿用到全客戶
# 計算分位數
seniority_q75 = df['DAY_DIFF'].quantile(0.75)
seniority_q50 = df['DAY_DIFF'].quantile(0.5)
seniority_q25 = df['DAY_DIFF'].quantile(0.25)
mml_q75 = df['A08'].quantile(0.75)
ag_q90 = (df['A01'] + df['A02']).quantile(0.9)
c800_q91 = df['A09'].quantile(0.91)
digital_q75 = (df['A08'] + df['A07']).quantile(0.75)

In [6]:
def classify(row):
    if row['IS_FB'] == 1 and row['IS_EMP'] == 0 and row['HIGH_LV'] >= 2:
        return 1
    elif row['IS_FB'] == 1 and row['HIGH_LV'] < 2 and row['SUM_of_STEP'] > 0:
        return 2
    elif row['IS_FB'] == 1 and row['HIGH_LV'] < 2 and (pd.isnull(row['SUM_of_STEP']) or row['SUM_of_STEP'] == 0) and row['A08'] >= mml_q75:
        return 3
    elif row['IS_FB'] == 1 and row['HIGH_LV'] < 2 and (pd.isnull(row['SUM_of_STEP']) or row['SUM_of_STEP'] == 0) and row['A08'] < mml_q75:
        return 4
    elif row['IS_FB'] == 0 and row['SUM_ISSUE_DAYS'] > 0:
        return 5
    elif row['IS_FB'] == 0 and (pd.isnull(row['SUM_ISSUE_DAYS']) or row['SUM_ISSUE_DAYS'] == 0) and row['A09'] >= c800_q91:
        return 6
    elif row['IS_FB'] == 0 and (pd.isnull(row['SUM_ISSUE_DAYS']) or row['SUM_ISSUE_DAYS'] == 0) and row['A09'] < c800_q91 and (row['A01'] + row['A02']) >= ag_q90:
        return 7
    elif row['IS_FB'] == 0 and (pd.isnull(row['SUM_ISSUE_DAYS']) or row['SUM_ISSUE_DAYS'] == 0) and row['A09'] < c800_q91 and (row['A01'] + row['A02']) < ag_q90 and (row['A08'] + row['A07']) >= digital_q75:
        return 8
    elif row['IS_FB'] == 0 and (pd.isnull(row['SUM_ISSUE_DAYS']) or row['SUM_ISSUE_DAYS'] == 0) and row['A09'] < c800_q91 and (row['A01'] + row['A02']) < ag_q90 and (row['A08'] + row['A07']) < digital_q75 and row['DAY_DIFF'] >= seniority_q75:
        return 9
    elif row['IS_FB'] == 0 and (pd.isnull(row['SUM_ISSUE_DAYS']) or row['SUM_ISSUE_DAYS'] == 0) and row['A09'] < c800_q91 and (row['A01'] + row['A02']) < ag_q90 and (row['A08'] + row['A07']) < digital_q75 and row['DAY_DIFF'] < seniority_q75 and row['DAY_DIFF'] >= seniority_q50:
        return 10
    elif row['IS_FB'] == 0 and (pd.isnull(row['SUM_ISSUE_DAYS']) or row['SUM_ISSUE_DAYS'] == 0) and row['A09'] < c800_q91 and (row['A01'] + row['A02']) < ag_q90 and (row['A08'] + row['A07']) < digital_q75 and row['DAY_DIFF'] < seniority_q50 and row['DAY_DIFF'] >= seniority_q25:
        return 11
    elif row['IS_FB'] == 0 and (pd.isnull(row['SUM_ISSUE_DAYS']) or row['SUM_ISSUE_DAYS'] == 0) and row['A09'] < c800_q91 and (row['A01'] + row['A02']) < ag_q90 and (row['A08'] + row['A07']) < digital_q75 and row['DAY_DIFF'] < seniority_q25:
        return 12
    else:
        if row['DAY_DIFF'] >= seniority_q75:
            return 9
        elif row['DAY_DIFF'] < seniority_q75 and row['DAY_DIFF'] >= seniority_q50:
            return 10
        elif row['DAY_DIFF'] < seniority_q50 and row['DAY_DIFF'] >= seniority_q25:
            return 11
        else:
            return 12

In [12]:
# 對DataFrame應用分類函數
df['CLASS'] = df.apply(classify, axis=1)

# 顯示結果
df.head()

,ID,FIRSTDT,DAY_DIFF,SOURCE,IS_CONTRACT_APC,IS_CONTRACT_INC,IS_EMP,IS_CLAIM,IS_FB,IS_MEMBER,...,COUNT_H_HOSPITAL,COUNT_I_INVESTMENT,COUNT_IS_VARIABLE_RATE,COUNT_L_LONGTERM_CARE,COUNT_M_MAJOR_ILLNESS,COUNT_R_REIMBURSEMENT,COUNT_S_SURGERY,COUNT_W_WAIVER,COUNT_Z_OTHER,CLASS
5893046,HDE3AB1D7FABF8A5DD,03JUN2022,759,FitBack,0,0,0,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2814802,E20F8EF37CBC11F50D,21APR2016,2993,契約被保人,1,1,0,1,1,1,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1
7386176,L260F7DE324F056646,14JUN2006,6592,契約要保人,1,1,1,0,1,1,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,11
7584176,L2E8A69D51BDDB0029,14JAN2011,4917,契約要保人,1,1,0,0,1,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1
6892340,L10A2D01E7CC97BF02,20SEP2004,7224,契約被保人,1,1,0,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [13]:
# 計算 df['result'] 各值的出現次數和占比
result_counts = df['CLASS'].value_counts().sort_index()
result_percentages = df['CLASS'].value_counts(normalize=True).sort_index() * 100

print(result_counts)
print(result_percentages)

CLASS
1      40263
2     357648
3     286668
4     317375
5     100144
6     253478
7     218651
8     282827
9     549199
10    583212
11    601482
12    618846
Name: count, dtype: int64
CLASS
1      0.956413
2      8.495620
3      6.809551
4      7.538969
5      2.378834
6      6.021151
7      5.193866
8      6.718311
9     13.045748
10    13.853698
11    14.287686
12    14.700153
Name: proportion, dtype: float64

In [14]:
# 想篩選的ID列表
id_list = ['A18434FFF04818EB88', 'F2145A73B19B29060F', 'S17E435DA94E7D0BAB', 'U25C08B91577F3BBBF']

# 使用isin方法篩選DataFrame
filtered_data = df[df['ID'].isin(id_list)]
filtered_data

,ID,FIRSTDT,DAY_DIFF,SOURCE,IS_CONTRACT_APC,IS_CONTRACT_INC,IS_EMP,IS_CLAIM,IS_FB,IS_MEMBER,...,COUNT_H_HOSPITAL,COUNT_I_INVESTMENT,COUNT_IS_VARIABLE_RATE,COUNT_L_LONGTERM_CARE,COUNT_M_MAJOR_ILLNESS,COUNT_R_REIMBURSEMENT,COUNT_S_SURGERY,COUNT_W_WAIVER,COUNT_Z_OTHER,CLASS
3955577,F2145A73B19B29060F,11JUN1997,9882,契約要保人,1,1,1,1,1,1,...,1.0,1.0,4.0,1.0,0.0,0.0,1.0,0.0,0.0,9
349864,A18434FFF04818EB88,21NOV2008,5701,契約被保人,1,1,0,0,1,1,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
12619119,U25C08B91577F3BBBF,21SEP2006,6493,官網,1,1,1,0,1,1,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,11
11174853,S17E435DA94E7D0BAB,18MAY1992,11732,契約要保人,1,1,1,0,1,1,...,1.0,1.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,9

# 跑全客群後儲存 ABT.csv

In [16]:
# 數位客戶
df = df_unique
len(df)

13105329

In [7]:
# 使用數位客戶的分位數
seniority_q75=9867.0
seniority_q50=8196.0
seniority_q25=4172.0
mml_q75=23.0
ag_q90=12.0
c800_q91=1.0
digital_q75=24.0

In [8]:
# 對DataFrame應用分類函數
df['CLASS'] = df.apply(classify, axis=1)

# 顯示結果
df.head()

,ID,FIRSTDT,DAY_DIFF,SOURCE,IS_CONTRACT_APC,IS_CONTRACT_INC,IS_EMP,IS_CLAIM,IS_FB,IS_MEMBER,...,COUNT_H_HOSPITAL,COUNT_I_INVESTMENT,COUNT_IS_VARIABLE_RATE,COUNT_L_LONGTERM_CARE,COUNT_M_MAJOR_ILLNESS,COUNT_R_REIMBURSEMENT,COUNT_S_SURGERY,COUNT_W_WAIVER,COUNT_Z_OTHER,CLASS
0,#005432F5B4D312911,05JUN1993,11349,意外險,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9
1,#010A3014A265DF94D,19APR1993,11396,意外險,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9
2,#02238ADE059241E68,16JUN1993,11338,意外險,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9
3,#023D96CE3BF169959,05JUN1993,11349,意外險,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9
4,#0328BA853B310F5DF,16JUN1993,11338,意外險,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9

In [9]:
# 計算 df['result'] 各值的出現次數和占比
result_counts = df['CLASS'].value_counts().sort_index()
result_percentages = df['CLASS'].value_counts(normalize=True).sort_index() * 100

print(result_counts)
print(result_percentages)

CLASS
1       40479
2      358301
3      288095
4      320820
5      185311
6      410699
7      402788
8      378607
9     2739330
10    2219465
11    2832920
12    2928514
Name: count, dtype: int64
CLASS
1      0.308874
2      2.734010
3      2.198304
4      2.448012
5      1.414013
6      3.133832
7      3.073467
8      2.888955
9     20.902413
10    16.935592
11    21.616550
12    22.345978
Name: proportion, dtype: float64

In [10]:
# 想篩選的ID列表
id_list = ['A18434FFF04818EB88', 'F2145A73B19B29060F', 'S17E435DA94E7D0BAB', 'U25C08B91577F3BBBF']

# 使用isin方法篩選DataFrame
filtered_data = df[df['ID'].isin(id_list)]
filtered_data

,ID,FIRSTDT,DAY_DIFF,SOURCE,IS_CONTRACT_APC,IS_CONTRACT_INC,IS_EMP,IS_CLAIM,IS_FB,IS_MEMBER,...,COUNT_H_HOSPITAL,COUNT_I_INVESTMENT,COUNT_IS_VARIABLE_RATE,COUNT_L_LONGTERM_CARE,COUNT_M_MAJOR_ILLNESS,COUNT_R_REIMBURSEMENT,COUNT_S_SURGERY,COUNT_W_WAIVER,COUNT_Z_OTHER,CLASS
349864,A18434FFF04818EB88,21NOV2008,5701,契約被保人,1,1,0,0,1,1,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
3955577,F2145A73B19B29060F,11JUN1997,9882,契約要保人,1,1,1,1,1,1,...,1.0,1.0,4.0,1.0,0.0,0.0,1.0,0.0,0.0,9
11174853,S17E435DA94E7D0BAB,18MAY1992,11732,契約要保人,1,1,1,0,1,1,...,1.0,1.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,9
12619119,U25C08B91577F3BBBF,21SEP2006,6493,官網,1,1,1,0,1,1,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,11

In [11]:
# 將結果保存為 CSV 文件
df.to_csv('ABT.csv', index=False)